export const DELETE_PERSON_RESET = "DELETE_PERSON_RESET";
export const DELETE_PERSON_REQUEST = "DELETE_PERSON_REQUEST";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";
export const DELETE_PERSON_ERROR = "DELETE_PERSON_ERROR";
