export const GET_PERSONS_RESET = "GET_PERSONS_RESET";
export const GET_PERSONS_REQUEST = "GET_PERSONS_REQUEST";
export const GET_PERSONS_SUCCESS = "GET_PERSONS_SUCCESS";
export const GET_PERSONS_ERROR = "GET_PERSONS_ERROR";
