export const UPDATE_PERSON_RESET = "UPDATE_PERSON_RESET";
export const UPDATE_PERSON_REQUEST = "UPDATE_PERSON_REQUEST";
export const UPDATE_PERSON_SUCCESS = "UPDATE_PERSON_SUCCESS";
export const UPDATE_PERSON_ERROR = "UPDATE_PERSON_ERROR";
